[theme]
base = "light"

# General color setup
textColor = "#dfdfdfff"
primaryColor = "#00d492"
backgroundColor = "#131435ff"
secondaryBackgroundColor = "#ffffff"

# Widgets
showWidgetBorder = true
borderColor = "#1c1c3dff"

# Base text
font = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
baseFontWeight = 400
baseFontSize = 20

# Heading text
headingFont = "'Open Sans':https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
headingFontWeights = [600, 300, 600]
headingFontSizes = ["3rem", "2rem", "1rem"]